siteshop/shop/urls.py
from django.conf.urls import url
from .views import views_product, views_list_product, views_order, SuccessOrder


app_name = 'shop'

urlpatterns = [
    url(r'^products/$', views_list_product, name="products"),
    url(r'^product/(?P<slug>[\w-]+)/$', views_product, name="product"),
    url(r'^order/(?P<slug>[\w-]+)/$', views_order, name="order"),
    url(r'^order-seccuss/$', SuccessOrder.as_view(), name='order-seccuss'),
]

siteshop/siteshop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from shop.views import views_list_product
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views_list_product, name="index"),
    url(r'^shop/', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteshop/shop/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

STATUS = (
    ("Пол.", "Получено", ),
    ("Обр.", "Обработано", ),
    ("Отп.", "Отправлено", ),
)


class Product(models.Model):

    name = models.CharField(max_length=150, verbose_name="Название")
    slug = models.SlugField(unique=True, verbose_name="URL")
    description = models.TextField(max_length=500, verbose_name="Описание", blank=True)
    price = models.IntegerField(verbose_name="Стоимость")
    photo = models.ImageField(verbose_name="Фото")

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

        ordering = ['-id']

    def __str__(self):
        return self.name

    def _get_unique_slug(self):
        unique_slug = slugify(self.name)
        num = 1
        while Article.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save()


class Delivery(models.Model):

    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.IntegerField(verbose_name="Стоимость")
    delivery_period = models.CharField(max_length=50, verbose_name="Ориентировочное время доставки")

    class Meta:
        verbose_name = 'Доставка'
        verbose_name_plural = 'Доставки'

    def __str__(self):
        return "{name} | {price} руб.".format(name=self.name, price=self.price)


class Order(models.Model):

    product = models.ForeignKey(Product, verbose_name="Товар")
    count_product = models.IntegerField(verbose_name="Кол-во товара",
                                        default=1, validators=[MinValueValidator(1), MaxValueValidator(50)])
    delivery = models.ForeignKey(Delivery, verbose_name="Доставка")
    status = models.CharField(max_length=20, choices=STATUS, default=STATUS[0][0], verbose_name='Статус')
    name_client = models.CharField(max_length=150, verbose_name="Имя клиента")
    phone_client = models.CharField(max_length=150, verbose_name="Телефон клиента")
    adress_client = models.CharField(max_length=250, verbose_name="Адрес клиента")
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

        ordering = ['-date_created']

    def __str__(self):
        return "Продукт: {product}, Кол-во: {count_product}".format(
            product=self.product, count_product=self.count_product)

siteshop/shop/forms.py
from django.forms import ModelForm
from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['count_product', 'delivery', 'name_client', 'phone_client', 'adress_client', ]
        labels = {
            "adress_client": "Адресс",
            "phone_client": "Номер телефона",
            "name_client": "Имя",
        }

siteshop/shop/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Product, Order
from django.http import Http404
from .forms import OrderForm
from django.views.generic.base import TemplateView
from django.shortcuts import redirect


def views_list_product(request):
    product_list = Product.objects.all()
    paginator = Paginator(product_list, 5)

    page = request.GET.get('page', 1)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/products.html', {'products': products, }, RequestContext(request))


def views_product(request, slug):
    try:
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        raise Http404("Product does not exist")

    return render(request, 'shop/product.html', {'product': product, }, RequestContext(request))


def views_order(request, slug):

    try:
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        raise Http404("Product does not exist")

    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            order = Order()

            order.count_product = form.cleaned_data['count_product']
            order.delivery = form.cleaned_data['delivery']
            order.name_client = form.cleaned_data['name_client']
            order.phone_client = form.cleaned_data['phone_client']
            order.adress_client = form.cleaned_data['adress_client']
            order.product = product

            order.save()
            return redirect("shop:order-seccuss")
    else:
        form = OrderForm()

    return render(request, 'shop/order.html',
                  {'form': form, 'product': product}, RequestContext(request))


class SuccessOrder(TemplateView):
    template_name = 'shop/success_order.html'

siteshop/shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no">
    
	<title>{% block title %}Магазин{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'style/index.css' %}">

	{% block styles %}
	{% endblock %}
</head>
<body>
	<div class="conteiner-fluid text-center">
		<div class="row main-conteiner">
			<div class="row head-block">
				<div class="col-md-12">
					<a class="pull-left logo" href="{% url 'index' %}">SHOP</a>
				</div>
			</div>
			<div class="row content">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>

	{% block javascript %}
	    <script src="{% static 'js/jquery.js'%}" charset="utf-8"></script>
		<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
	{% endblock %}	
</body>
</html>

siteshop/shop/templates/shop/order.html
{% extends 'base.html' %}


{% load static %}

{% block title %}
	Товары
{% endblock %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'style/order.css' %}">
{% endblock %}

{% block content %}
	<form action="." method="post">
		<div class="col-md-12 col-sm-12">
			<div class="col-md-3 col-sm-3">
				<h3 class="product-title">ТОВАР</h3>
			</div>

			<div class="col-md-3 col-sm-3 hidden-xs"> 
				название
			</div>

			<div class="col-md-3 col-sm-3 hidden-xs"> 
				<label for="{{ form.count_product.id_for_label }}">кол-во.</label>
			</div>
			
			<div class="col-md-3 col-sm-3 hidden-xs">
				итог
			</div>
		</div>

		<div class="col-line col-md-12 col-sm-12">	
			<hr class="line">	
		</div>

		<div class="col-md-12 col-sm-12">	
			<div class="col-md-3 col-sm-3">
				<div class="product-image" style="background-image: url(/media/{{product.photo}});"></div>
			</div>
			<div class="col-md-3 col-sm-3">
				{{product.name}}
			</div>
			<div class="col-md-3 col-sm-3">
				{{ form.count_product.errors }}
				{{ form.count_product }}
			</div>
			<div class="col-md-3 col-sm-3">
				<div id="result-price-product">	</div>
				<div>
					<div class="inline" id="price-product">{{product.price}}</div>
					<div class="inline"> руб. x </div>
					<div class="inline" id="count-product"></div>	
				</div>
			</div>
		</div>

		<div class="col-md-12 col-sm-12 col-create-order text-left">
			<h3 class="product-title">Оформление заказа</h3>
		</div>

		<div class="col-line col-md-12 col-sm-12">	
			<hr class="line">	
		</div>

		<div class="col-line col-md-12 col-sm-12 text-center">
			<div class="block-order-form inline">	
				<div class="row order-form-item">
					{{ form.name_client.errors }}
					<div class="col-md-4 col-sm-4 text-left">
						<label for="{{ form.name_client.id_for_label }}">Имя</label>
					</div>
					<div class="col-md-8 col-sm-8 input-block">
						{{ form.name_client }}
					</div>
				</div>
				<div class="row order-form-item">
					{{ form.phone_client.errors }}
					<div class="col-md-4 col-sm-4 text-left">
						<label for="{{ form.phone_client.id_for_label }}">Телефон</label>
					</div>
					<div class="col-md-8 col-sm-8 input-block">
						{{ form.phone_client }}
					</div>
				</div>
				<div class="row order-form-item">
					{{ form.adress_client.errors }}
					<div class="col-md-4 col-sm-4 text-left">
						<label for="{{ form.adress_client.id_for_label }}">Адрес</label>
					</div>
					<div class="col-md-8 col-sm-8 input-block text-left">
						{{ form.adress_client }}
					</div>
				</div>
				<div class="row order-form-item">
					{{ form.delivery.errors }}
					<div class="col-md-4 col-sm-4 text-left">
						<label for="{{ form.delivery.id_for_label }}">Способ доставки</label>
					</div>
					<div class="col-md-8 col-sm-8 input-block">
							{{ form.delivery }}
					</div>
				</div>
			</div>
		</div>

		{% csrf_token %}
		<button class="btn-submit" type="submit" name="submit" value="submit">ОФОРМИТЬ ЗАКАЗ</button>
	</form>
{% endblock %}

{% block javascript %}
	<script src="{% static 'js/jquery.js' %}">	</script>
	<script src="{% static 'js/order.js' %}">	</script>
{% endblock %}

siteshop/shop/templates/shop/product.html
{% extends 'base.html' %}


{% load static %}

{% block title %}
	{{product.name}}
{% endblock %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'style/product.css' %}">
{% endblock %}

{% block content %}
	<div class="image-product-col col-md-6">
		<div class="image-product" style="background-image: url(/media/{{product.photo}});"></div>
	</div>
	<div class="data-col col-md-6">
		<div class="name-product text-left">
			{{product.name}}
		</div>

		<div class="description-product text-left">
			{{product.description}}
		</div>
		<div class="price-product text-left">
			Стоимость: {{ product.price }} руб.
		</div>

		<div class="order-product text-left">
			<a href="{% url 'shop:order' slug=product.slug %}" class="btn-order">ЗАКАЗАТЬ</a>
		</div>	
	</div>
{% endblock %}

{% block javascript %}
	
{% endblock %}

siteshop/shop/templates/shop/products.html
{% extends 'base.html' %}


{% load static %}

{% block title %}
	Товары
{% endblock %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'style/products.css' %}">
{% endblock %}

{% block content %}
	{% for product in products %}
		<div class="row product">
			<div class="col-md-4">
				<div class="image-product" style="background-image: url(/media/{{product.photo}});"></div>
			</div>
			
			<div class="col-md-8">
			<div class="name-product text-left">
				{{ product.name|upper }}
			</div>
			<div class="description-product text-left">
				{{ product.description|truncatechars:300 }}
			</div>
			<div class="price-product text-left">
				<div class="inline pull-left">
					СТОИМОСТЬ: {{ product.price}} руб.
				</div>
				<div class="inline pull-right">
					<a href="{% url 'shop:product' slug=product.slug %}" class="btn-read-more">ПОДРОБНЕЕ..</a>
				</div>
			</div>
			</div>

		</div>
	{% endfor %}

	<div class="pagination">
		<span class="step-links">
			{% if products.has_previous %}
				<a href="?page={{ products.previous_page_number }}">предыдущая</a>
			{% endif %}

			<span class="current">
				Стр<span class=""></span> {{ products.number }} из {{ products.paginator.num_pages }}.
			</span>

			{% if products.has_next %}
				<a href="?page={{ products.next_page_number }}">следующая</a>
			{% endif %}
		</span>
	</div>
{% endblock %}

{% block javascript %}
	
{% endblock %}

siteshop/shop/templates/shop/success_order.html
{% extends 'base.html' %}


{% load static %}

{% block title %}
	Товары
{% endblock %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'style/order.css' %}">
{% endblock %}

{% block content %}
	<h2>
		Ваш заказ принят!
	</h2>
	<a href="{% url 'index' %}">Вернуться на главную</a>
{% endblock %}

{% block javascript %}
	<script src="{% static 'js/jquery.js' %}">	</script>
	<script src="{% static 'js/order.js' %}">	</script>
{% endblock %}